# Generated by Django 6.0.3 on 2026-03-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment_likes_count_comment_parent_comment_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
