# Generated by Django 6.0.3 on 2026-05-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbook',
            name='character',
            field=models.IntegerField(choices=[(1, 'Character 1'), (2, 'Character 2'), (3, 'Character 3'), (4, 'Character 4'), (5, 'Character 5')], default=1),
        ),
    ]
